# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shhh < Formula
  desc "Natural language to shell commands"
  homepage "https://github.com/rfizzle/shhh"
  version "0.11.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rfizzle/shhh/releases/download/v0.11.12/shhh_0.11.12_darwin_amd64.tar.gz"
      sha256 "73e3e92732c7e5de3d93a0b7939e0441bef2319948db766f2c6268f3d09d9300"

      define_method(:install) do
        bin.install "shhh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rfizzle/shhh/releases/download/v0.11.12/shhh_0.11.12_darwin_arm64.tar.gz"
      sha256 "a6fc5a10acb0a8f332ca0972322daa53ee363a02a588b4a4cd402897a5d4b215"

      define_method(:install) do
        bin.install "shhh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rfizzle/shhh/releases/download/v0.11.12/shhh_0.11.12_linux_amd64.tar.gz"
      sha256 "3ec629183142d35e6093bf7b8011ab64e0043f652a80604256fd6cfcd3548f03"
      define_method(:install) do
        bin.install "shhh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rfizzle/shhh/releases/download/v0.11.12/shhh_0.11.12_linux_arm64.tar.gz"
      sha256 "19de417672837d04739a5851df1631cd04e25712276183d602c0864ee5c4ec90"
      define_method(:install) do
        bin.install "shhh"
      end
    end
  end

  test do
    system "#{bin}/shhh", "--version"
  end
end
