# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shhh < Formula
  desc "Natural language to shell commands"
  homepage "https://github.com/rfizzle/shhh"
  version "0.16.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rfizzle/shhh/releases/download/v0.16.2/shhh_0.16.2_darwin_amd64.tar.gz"
      sha256 "059093bf29942f6750d54235d8a1005aa062d6db4a73976c4fa6917232dcaf7e"

      define_method(:install) do
        bin.install "shhh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rfizzle/shhh/releases/download/v0.16.2/shhh_0.16.2_darwin_arm64.tar.gz"
      sha256 "4f474871ed1da468590f70a4bc53e581e08820775250f929018151f949c9895a"

      define_method(:install) do
        bin.install "shhh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rfizzle/shhh/releases/download/v0.16.2/shhh_0.16.2_linux_amd64.tar.gz"
      sha256 "e33ba9fe36607be15d73e26838ae9e4cc38e7032e1c7c4f546adc75f694c30cd"
      define_method(:install) do
        bin.install "shhh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rfizzle/shhh/releases/download/v0.16.2/shhh_0.16.2_linux_arm64.tar.gz"
      sha256 "3e3fe28a14ecf0157a989597d922d9ad644f61f330675fd40351bd70dd7988d3"
      define_method(:install) do
        bin.install "shhh"
      end
    end
  end

  test do
    system "#{bin}/shhh", "--version"
  end
end
