# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shhh < Formula
  desc "Natural language to shell commands"
  homepage "https://github.com/rfizzle/shhh"
  version "0.6.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rfizzle/shhh/releases/download/v0.6.8/shhh_0.6.8_darwin_amd64.tar.gz"
      sha256 "32a221611f1a061db94353fe8bc592f6c4d06c5a41e65125dbe1e8eb6b0da803"

      define_method(:install) do
        bin.install "shhh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rfizzle/shhh/releases/download/v0.6.8/shhh_0.6.8_darwin_arm64.tar.gz"
      sha256 "2a9b8eabc71fb5217d5a121a0cbe996125f3e3290a56bb21537060f32cc6fcf2"

      define_method(:install) do
        bin.install "shhh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rfizzle/shhh/releases/download/v0.6.8/shhh_0.6.8_linux_amd64.tar.gz"
      sha256 "296a9937a596a1028421965ca9e073dd22e1d544e349054d61bf3076d38d38fe"
      define_method(:install) do
        bin.install "shhh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rfizzle/shhh/releases/download/v0.6.8/shhh_0.6.8_linux_arm64.tar.gz"
      sha256 "81145c344e564872fac27bad0c971d741fd62a7961d26b53c1d3f645e9b1f340"
      define_method(:install) do
        bin.install "shhh"
      end
    end
  end

  test do
    system "#{bin}/shhh", "--version"
  end
end
